# Fichero : software de gestion

main.exe : main.cc funtion.cc alumno.cc profesor.cc

	g++ main.cc funtion.cc alumno.cc profesor.cc -o main.exe

Binario.exe : Binario.cc profesor.cc

	g++ Binario.cc profesor.cc -o Binario.exe

Binario_alumnos.exe : Binario_alumnos.cc alumno.cc

	g++ Binario:alumnos.cc alumno.cc -o Binario_alumnos.exe

